// EXACT soft-float x87 unit — implements x87_exact.h on top of Berkeley SoftFloat-3e
// (extF80, 8086 specialization).  See the header for the contract; this file also
// hosts the X87Exec dispatch that selects NATIVE (host x87) or EXACT at runtime.
//
// ---------------------------------------------------------------------------------
// BEHAVIOR SOURCES.  Everything "undefined" in the SDM was pinned by running the
// actual instruction on this host (scratchpad probe, session 24) and is reproduced
// exactly:
//   - fnsave pad words: the high 16 bits of the CW/SW/TW dwords read 0xFFFF.
//   - fnsave REGENERATES the tag word from the register contents for every
//     non-empty register (P6+ keeps only an empty bit internally); empty registers
//     keep tag 11 and their raw bytes.
//   - SW.ES and SW.B are DERIVED: ES = ((flags & ~masks) & 0x3F) != 0, B = ES.
//     A stored ES bit inconsistent with the flags is ignored by frstor (probed:
//     ES=1/flags=0 image does not fault and saves back ES=0; PE=1-unmasked/ES=0
//     image DOES fault at the next waiting instruction).
//   - fldcw normalization: CW := (value & 0x1F3F) | 0x0040 (bit 6 forced, 13-15 and
//     7 cleared).
//   - #MF delivery is DEFERRED: an op that raises a new unmasked exception COMPLETES
//     (flags + ES recorded, result delivered per the abort/deferred-store rules) and
//     the fault materializes at the NEXT waiting fp instruction.  The EXACT unit
//     returns -1 from that next op (image untouched), mirroring the native thunk
//     whose frstor+INSN faults there.  fwait delivers likewise.  No-wait forms
//     (fnstsw, fnstcw, fnclex) execute despite a pending exception.
//   - condition codes: arithmetic/store/round ops write C1 = "significand was
//     incremented by rounding" (0 when exact or aborted) and PRESERVE C0/C2/C3;
//     loads/fxch/fchs/fabs/ffree/constants clear C1 and preserve the rest;
//     compares/ftst/fxam write all four; fnstsw/fnstcw/fldcw/fnclex/fwait preserve
//     all four.  Masked stack overflow sets C1=1, underflow C1=0.
//   - the constant loads (fldpi/fldlg2/fldln2/fldl2e) honor RC: the internal
//     values carry >64 significant bits with a guard bit of 1 and nonzero sticky,
//     so RN and +inf round the 64-bit base up, -inf and chop truncate (positive
//     constants).  Host-verified patterns (RN): pi=4000:C90FDAA22168C235,
//     lg2=3FFD:9A209A84FBCFF799, ln2=3FFE:B17217F7D1CF79AC,
//     l2e=3FFF:B8AA3B295C17F0BC.  No flags, C1=0.
//   - masked responses (probed): underflow on a register op writes the real
//     indefinite (FFFF:C000...0) over the destination and still pops; stores from an
//     empty ST0 write the format indefinite to memory and still pop; overflow on a
//     push decrements TOP and writes the indefinite.  fst m32/m64 of an extended
//     denormal raises U/P but NOT D.  fist invalid (out of range / NaN) raises IE
//     only (no PE) and stores the integer indefinite.
//   - unmasked O/U on a REGISTER destination store the result with the exponent
//     wrapped by -/+24576 (probed via fscale: 2^16383*2^1000 unmasked -> 23E6:8000,
//     i.e. biased 17383+16383-24576); on a MEMORY store nothing is stored and the
//     stack does not pop.
//
// PRECISION CONTROL (CW.PC -> extF80_roundingPrecision) applies ONLY to
// add/sub/mul/div/sqrt — never to loads, stores, conversions, frndint, fscale or
// the transcendentals (probed: fld under PC=32 copies all 64 bits).  PC=01
// (reserved) is treated as 64-bit and never generated by the corpus.
//
// TRANSCENDENTALS (fsin/fcos/fsincos/fpatan/fyl2x/f2xm1) are DETERMINISTIC pure
// integer/extF80 code, close to but not bit-equal with silicon (accepted design,
// see x87_exact.h).  Methods:
//   - fsin/fcos/fsincos: argument reduction modulo the x87's own 66-bit pi/2
//     (0xC90FDAA22168C234C x 2^-65, exactly the value silicon uses, so even huge
//     arguments track the hardware's "wrong" pi) performed EXACTLY in 192-bit
//     integer fixed point (x*2^127 long-divided by pi/2*2^127, nearest quotient,
//     exact remainder), then odd/even Taylor kernels of degree 21/22 on
//     |r| <= pi/4 evaluated in extF80 (round-nearest, 80-bit) — kernel error
//     ~2^-72, well under 1 ulp.  |x| >= 2^63: C2=1, operand untouched (hardware
//     rule).  All internal arithmetic uses fixed RN/80 so the guest RC never
//     influences the result (documented divergence: hardware rounds the final
//     result per RC; ours is the RN value).
//   - fpatan: atan2 special cases use the RN-rounded pi family; the kernel halves
//     the argument four times via u' = u/(1+sqrt(1+u^2)) then applies an odd
//     Taylor polynomial of degree 15 and multiplies by 16 (error ~2^-74).
//   - fyl2x: log2(m) for m in [sqrt2/2, sqrt2) via the atanh series
//     s=(m-1)/(m+1), 2/ln2 * sum s^(2k+1)/(2k+1) to k=13 (~2^-78), plus the
//     exponent; multiplied by y in extF80.
//   - f2xm1: 2^x-1 = expm1(x*ln2) by a degree-20 Taylor kernel (~2^-76 for
//     |x| <= 1; outside the SDM-defined domain the same series runs anyway —
//     deterministic, finite, explicitly "undefined" territory).
//   - flags: PE on every inexact numeric path, DE for denormal inputs, UE when the
//     delivered result is denormal, IE/indefinite for the invalid cases; C1=0
//     (hardware's per-result roundup bit cannot be reproduced without bit-equal
//     results); fsin/fcos/fsincos write C2 (0 reduced, 1 unreduced), the rest
//     preserve it.
// ---------------------------------------------------------------------------------
#include "engine/engine_priv.h"
#include "engine/x87_exact.h"
#include <cstring>

extern "C" {
#include "softfloat.h"
#include "internals.h"          // softfloat_roundPackToExtF80, normSubnormal (fscale)
}

namespace tj::engine {

// =============================== mode + dispatch ==================================

static FpuMode g_fpuMode =
#ifdef _M_IX86
    FpuMode::Native;
#else
    FpuMode::Exact;
#endif
static bool g_x87Fault = false;

void EngineSetFpuMode(FpuMode m) { g_fpuMode = m; }
FpuMode EngineGetFpuMode() { return g_fpuMode; }
bool X87TakeFault() { bool f = g_x87Fault; g_x87Fault = false; return f; }

bool X87Exec(CpuState& s, uint8_t op, uint8_t modrm, uint32_t ea) {
#ifdef _M_IX86
    if (g_fpuMode == FpuMode::Native) return X87NativeExec(s, op, modrm, ea);
#endif
    // FAST mode (TJ_ENG_FAST=1, non-x86 hosts): host-double core first; anything it
    // does not reproduce bit-equivalently falls through to the EXACT unit below on
    // the untouched image (x87_fast.cpp documents the contract).
    static const bool fast = X87FastWanted();
    if (fast) {
        int rf = X87FastExec(s, op, modrm, ea);
        if (rf != kX87FastFallback) {
            if (rf < 0) { g_x87Fault = true; return false; }
            return rf != 0;
        }
    }
    int r = X87ExactExec(s, op, modrm, ea);
    if (r < 0) { g_x87Fault = true; return false; }
    return r != 0;
}

// ================================ SW/CW bits ======================================

namespace {

constexpr uint16_t kIE = 0x01, kDE = 0x02, kZE = 0x04, kOE = 0x08, kUE = 0x10,
                   kPE = 0x20, kSF = 0x40;

inline extFloat80_t MakeExt(uint16_t se, uint64_t sig) {
    extFloat80_t v; v.signif = sig; v.signExp = se; return v;
}
const extFloat80_t kIndef = { 0xC000000000000000ull, 0xFFFF };
const extFloat80_t kOne   = { 0x8000000000000000ull, 0x3FFF };

enum Cls { cZero, cNorm, cDenorm, cInf, cQNaN, cSNaN, cUnsupp };

Cls ClassOf(extFloat80_t v) {
    int exp = v.signExp & 0x7FFF; uint64_t sig = v.signif;
    if (exp == 0x7FFF) {
        if (!(sig >> 63)) return cUnsupp;                  // pseudo-inf / pseudo-NaN
        if (!(sig << 1)) return cInf;
        return (sig & 0x4000000000000000ull) ? cQNaN : cSNaN;
    }
    if (exp == 0) return sig ? cDenorm : cZero;            // pseudo-denormals: cDenorm
    return (sig >> 63) ? cNorm : cUnsupp;                  // unnormal
}
inline bool IsNaNC(Cls c) { return c == cQNaN || c == cSNaN || c == cUnsupp; }

// tag as fnsave regenerates it (probed): from the VALUE, empty handled by caller
int TagOf(extFloat80_t v) {
    int exp = v.signExp & 0x7FFF; uint64_t sig = v.signif;
    if (exp == 0x7FFF) return 2;
    if (exp == 0) return sig ? 2 : 1;
    return (sig >> 63) ? 0 : 2;
}

// x87 RC field -> softfloat rounding mode (00 nearest, 01 down, 10 up, 11 chop)
const uint8_t kRcMap[4] = { softfloat_round_near_even, softfloat_round_min,
                            softfloat_round_max, softfloat_round_minMag };
// x87 PC field -> precision (01 reserved: treat as 64)
const uint8_t kPcMap[4] = { 32, 64, 64, 80 };

uint16_t X87FlagsFromSf(uint8_t f) {
    uint16_t r = 0;
    if (f & softfloat_flag_invalid)  r |= kIE;
    if (f & softfloat_flag_infinite) r |= kZE;
    if (f & softfloat_flag_overflow) r |= kOE;
    if (f & softfloat_flag_underflow) r |= kUE;
    if (f & softfloat_flag_inexact)  r |= kPE;
    return r;
}

// |a| > |b| for canonical extF80 (exp field then significand — monotonic for the
// canonical values that arise as op results)
bool MagGT(extFloat80_t a, extFloat80_t b) {
    int ea = a.signExp & 0x7FFF, eb = b.signExp & 0x7FFF;
    if (ea != eb) return ea > eb;
    return a.signif > b.signif;
}

// ================================ FPU state =======================================

struct Fpu {
    uint16_t cw;
    uint16_t flags;      // SW bits 0..6 (sticky exception flags + SF)
    int c0, c1, c2, c3;
    int top;
    uint8_t empty;       // bit per PHYSICAL register
    extFloat80_t r[8];   // physical registers

    int Phys(int i) const { return (top + i) & 7; }
    bool Empty(int i) const { return (empty >> Phys(i)) & 1; }
    extFloat80_t Get(int i) const { return r[Phys(i)]; }
    void Put(int i, extFloat80_t v) { r[Phys(i)] = v; empty &= ~(1u << Phys(i)); }
    void PopOne() { empty |= 1u << Phys(0); top = (top + 1) & 7; }
    void Pops(int n) { while (n--) PopOne(); }
    void PushSlot() { top = (top - 1) & 7; }

    bool Masked(uint16_t bit) const { return (cw & bit) != 0; }
    uint8_t Rc() const { return (cw >> 10) & 3; }
    uint8_t SfRound() const { return kRcMap[Rc()]; }
    uint8_t Prec() const { return kPcMap[(cw >> 8) & 3]; }
};

void LoadImage(Fpu& F, const uint8_t img[108]) {
    uint16_t sw, tw;
    memcpy(&F.cw, img + 0, 2);
    memcpy(&sw, img + 4, 2);
    memcpy(&tw, img + 8, 2);
    F.cw = (F.cw & 0x1F3F) | 0x0040;    // same normalization fldcw applies
    F.flags = sw & 0x7F;
    F.c0 = (sw >> 8) & 1; F.c1 = (sw >> 9) & 1; F.c2 = (sw >> 10) & 1; F.c3 = (sw >> 14) & 1;
    F.top = (sw >> 11) & 7;
    F.empty = 0;
    for (int p = 0; p < 8; ++p)
        if (((tw >> (2 * p)) & 3) == 3) F.empty |= 1u << p;
    for (int i = 0; i < 8; ++i) {       // image slots are LOGICAL (ST0 first)
        int p = F.Phys(i);
        memcpy(&F.r[p].signif, img + 28 + 10 * i, 8);
        memcpy(&F.r[p].signExp, img + 28 + 10 * i + 8, 2);
    }
}

void StoreImage(const Fpu& F, uint8_t img[108]) {
    uint16_t sw = (uint16_t)(F.flags | (F.c0 << 8) | (F.c1 << 9) | (F.c2 << 10) |
                             (F.top << 11) | (F.c3 << 14));
    if ((F.flags & ~F.cw) & 0x3F) sw |= 0x8080;            // derived ES + B
    uint16_t tw = 0, pad = 0xFFFF;
    for (int p = 0; p < 8; ++p) {
        int t = ((F.empty >> p) & 1) ? 3 : TagOf(F.r[p]);
        tw |= (uint16_t)(t << (2 * p));
    }
    memcpy(img + 0, &F.cw, 2); memcpy(img + 2, &pad, 2);
    memcpy(img + 4, &sw, 2);   memcpy(img + 6, &pad, 2);
    memcpy(img + 8, &tw, 2);   memcpy(img + 10, &pad, 2);
    memset(img + 12, 0, 16);                               // FIP/FCS/FOO/FOS
    for (int i = 0; i < 8; ++i) {
        int p = ((F.top + i) & 7);
        memcpy(img + 28 + 10 * i, &F.r[p].signif, 8);
        memcpy(img + 28 + 10 * i + 8, &F.r[p].signExp, 2);
    }
}

// ============================ rounding-aware op runs ==============================

typedef extFloat80_t (*BinFn)(extFloat80_t, extFloat80_t);

struct BinRes { extFloat80_t v; uint8_t sf; bool up; };

// Run fn under (rc, prec); detect "significand incremented" (C1) by re-running
// with round-toward-zero and comparing magnitudes.
BinRes RunBin(BinFn f, extFloat80_t a, extFloat80_t b, uint8_t rcMode, uint8_t prec) {
    BinRes r;
    softfloat_roundingMode = rcMode;
    extF80_roundingPrecision = prec;
    softfloat_exceptionFlags = 0;
    r.v = f(a, b);
    r.sf = (uint8_t)softfloat_exceptionFlags;
    r.up = false;
    if (r.sf & softfloat_flag_inexact) {
        softfloat_roundingMode = softfloat_round_minMag;
        softfloat_exceptionFlags = 0;
        extFloat80_t t = f(a, b);
        r.up = MagGT(r.v, t);
    }
    extF80_roundingPrecision = 80;
    softfloat_exceptionFlags = 0;
    return r;
}

// exact multiply by 2^k for values the caller keeps in normal range (zero passes
// through; denormal inputs are normalized; a result still below the normal range
// is re-denormalized, chopping bits the callers never depend on)
extFloat80_t ScaleExact2k(extFloat80_t x, int32_t k) {
    int exp = x.signExp & 0x7FFF; uint64_t sig = x.signif;
    bool sign = (x.signExp >> 15) & 1;
    if (!sig && !exp) return x;
    if (!exp) exp = 1;
    if (!(sig >> 63)) {
        struct exp32_sig64 n = softfloat_normSubnormalExtF80Sig(sig);
        exp += n.exp; sig = n.sig;
    }
    exp += k;
    if (exp <= 0) {
        int sh = 1 - exp;
        if (sh > 63) return MakeExt((uint16_t)(sign ? 0x8000 : 0), 0);
        sig >>= sh; exp = 0;
    } else if (exp >= 0x7FFF) {
        return MakeExt((uint16_t)((sign ? 0x8000 : 0) | 0x7FFF), 0x8000000000000000ull);
    }
    return MakeExt((uint16_t)((sign ? 0x8000 : 0) | exp), sig);
}

inline int UnbiasedExp(extFloat80_t x) {           // for nonzero finite x
    int exp = x.signExp & 0x7FFF; uint64_t sig = x.signif;
    if (!exp) {
        struct exp32_sig64 n = softfloat_normSubnormalExtF80Sig(sig);
        return 1 + n.exp - 0x3FFF;
    }
    return exp - 0x3FFF;
}

enum WrapClass { wAddSub, wMul, wDiv };

// Recompute fn with the exponent bias hardware applies for an UNMASKED O/U on a
// register destination (result scaled by 2^wrap, wrap = -/+24576), by exact
// power-of-two pre-scaling of the operands so the final rounding is performed once
// at the wrapped magnitude.
BinRes RunBinWrapped(BinFn f, WrapClass wc, extFloat80_t a, extFloat80_t b,
                     uint8_t rcMode, uint8_t prec, int32_t wrap) {
    if (wc == wMul) {
        int ea = UnbiasedExp(a), eb = UnbiasedExp(b);
        int q = ea + eb + wrap;                    // wrapped product exponent (~in range)
        int da = q / 2 - ea, db = (q - q / 2) - eb;
        return RunBin(f, ScaleExact2k(a, da), ScaleExact2k(b, db), rcMode, prec);
    }
    if (wc == wDiv) {
        int ea = UnbiasedExp(a), eb = UnbiasedExp(b);
        int q = ea - eb + wrap;                    // wrapped quotient exponent
        int da = q / 2 - ea, db = -(q - q / 2) - eb;
        return RunBin(f, ScaleExact2k(a, da), ScaleExact2k(b, db), rcMode, prec);
    }
    // add/sub: scale both operands by 2^wrap.  A scaled operand that would leave
    // the exact range is far below one ulp of the other; substitute a same-signed
    // minimal denormal so the sticky/rounding effect survives.  If scaling UP would
    // overflow an operand, the un-wrapped result was exact (deep cancellation of
    // near-equal giants) — scale the exact result instead.
    int ba = (a.signExp & 0x7FFF), bb = (b.signExp & 0x7FFF);
    if (wrap > 0 && (ba + wrap > 0x7FF0 || bb + wrap > 0x7FF0)) {
        BinRes r = RunBin(f, a, b, softfloat_round_minMag, prec);  // exact -> mode moot
        r.v = ScaleExact2k(r.v, wrap);
        r.up = false; r.sf = 0;
        return r;
    }
    extFloat80_t sa, sb;
    if (wrap < 0 && ba + wrap < 64)                // (biased) far under denormal floor
        sa = MakeExt((uint16_t)(a.signExp & 0x8000), a.signif ? 1 : 0);
    else sa = ScaleExact2k(a, wrap);
    if (wrap < 0 && bb + wrap < 64)
        sb = MakeExt((uint16_t)(b.signExp & 0x8000), b.signif ? 1 : 0);
    else sb = ScaleExact2k(b, wrap);
    return RunBin(f, sa, sb, rcMode, prec);
}

// ============================ the exec engine =====================================

struct Exec {
    Fpu F;

    // ---- generic outcome helpers -------------------------------------------------
    // Raise IE for a stack fault; returns true if masked (caller proceeds with the
    // indefinite response), false to abort.
    bool StackFault(bool overflow) {
        F.flags |= kIE | kSF;
        F.c1 = overflow ? 1 : 0;
        return F.Masked(kIE);
    }
    // denormal-operand gate: true to continue (masked), false to abort
    bool DenormGate() {
        F.flags |= kDE;
        return F.Masked(kDE);
    }

    // Deliver a binary arithmetic result to register dst with full masked/unmasked
    // semantics.  Returns false when the op aborted (dest untouched, no pops).
    bool Deliver(BinFn fn, WrapClass wc, extFloat80_t a, extFloat80_t b,
                 uint8_t prec, extFloat80_t* out) {
        uint8_t rc = F.SfRound();
        BinRes r = RunBin(fn, a, b, rc, prec);
        uint16_t xf = X87FlagsFromSf(r.sf);
        if (xf & kIE) {                            // SNaN / inf-inf / 0*inf / 0/0 ...
            F.flags |= kIE;
            if (!F.Masked(kIE)) { F.c1 = 0; return false; }
            *out = r.v; F.c1 = 0; return true;
        }
        if (xf & kZE) {                            // divide by zero
            F.flags |= kZE;
            if (!F.Masked(kZE)) { F.c1 = 0; return false; }
            *out = r.v; F.c1 = 0; return true;
        }
        bool tiny = ((r.v.signExp & 0x7FFF) == 0) && r.v.signif;   // denormal result
        if (xf & kOE) {
            if (!F.Masked(kOE)) {
                // PE comes from the DELIVERED (wrapped) rounding, not the inf-round
                BinRes w = RunBinWrapped(fn, wc, a, b, rc, prec, -24576);
                F.flags |= kOE | (X87FlagsFromSf(w.sf) & kPE);
                *out = w.v; F.c1 = w.up ? 1 : 0; return true;
            }
            F.flags |= kOE | (xf & kPE);
            *out = r.v; F.c1 = r.up ? 1 : 0; return true;
        }
        if (!F.Masked(kUE) && ((xf & kUE) || tiny)) {   // unmasked #U: tininess alone
            BinRes w = RunBinWrapped(fn, wc, a, b, rc, prec, +24576);
            F.flags |= kUE | (X87FlagsFromSf(w.sf) & kPE);
            *out = w.v; F.c1 = w.up ? 1 : 0; return true;
        }
        F.flags |= xf;                             // masked UE and/or PE
        *out = r.v; F.c1 = r.up ? 1 : 0; return true;
    }

    // Full register-destination binary op: underflow/unsupported/SNaN/denormal
    // gates, then Deliver, then write + pops.  ca/cb are the RAW operand classes:
    // for a memory operand the class of the f32/f64/int bits BEFORE conversion
    // (the conversion quietens SNaNs and normalizes denormals, which would
    // otherwise hide the #IA/#D the hardware raises).
    void BinaryOp(BinFn fn, WrapClass wc, extFloat80_t a, extFloat80_t b,
                  Cls ca, Cls cb, int srcEmptyMask, int dst, int pops, uint8_t prec) {
        F.c1 = 0;
        if (srcEmptyMask) {
            if (!StackFault(false)) return;
            F.Put(dst, kIndef); F.Pops(pops); return;
        }
        if (ca == cUnsupp || cb == cUnsupp) {
            F.flags |= kIE;
            if (!F.Masked(kIE)) return;
            F.Put(dst, kIndef); F.Pops(pops); return;
        }
        if (ca == cSNaN || cb == cSNaN) {
            F.flags |= kIE;
            if (!F.Masked(kIE)) return;
            softfloat_exceptionFlags = 0;
            extFloat80_t r = fn(a, b);             // 8086 NaN propagation
            softfloat_exceptionFlags = 0;
            F.Put(dst, r); F.Pops(pops); return;
        }
        if (ca == cQNaN || cb == cQNaN) {
            softfloat_exceptionFlags = 0;
            extFloat80_t r = fn(a, b);
            softfloat_exceptionFlags = 0;
            F.Put(dst, r); F.Pops(pops); return;
        }
        // #D for a denormal operand — EXCEPT division by zero, whose #Z/#IA path
        // exits before the operands are examined for denormality (probed: fdiv
        // den/0 -> ZE only; fdiv 0/den -> DE)
        bool zeroDivisor = (wc == wDiv) && (cb == cZero);
        if (!zeroDivisor && (ca == cDenorm || cb == cDenorm))
            if (!DenormGate()) return;
        extFloat80_t out;
        if (!Deliver(fn, wc, a, b, prec, &out)) return;
        F.Put(dst, out); F.Pops(pops);
    }

    // ---- compares ----------------------------------------------------------------
    void SetCmp(int c0, int c2, int c3) { F.c0 = c0; F.c1 = 0; F.c2 = c2; F.c3 = c3; }

    // 3-way compare of canonical non-NaN values
    void OrderedCmp(extFloat80_t a, extFloat80_t b) {
        bool za = !(a.signExp & 0x7FFF) && !a.signif;
        bool zb = !(b.signExp & 0x7FFF) && !b.signif;
        int sa = (a.signExp >> 15) & 1, sb = (b.signExp >> 15) & 1;
        // inf handled by magnitude compare (7FFF:8000.. is the largest canonical)
        if (za && zb) { SetCmp(0, 0, 1); return; }
        if (za) { SetCmp(sb ? 0 : 1, 0, 0); return; }      // a=0: a<b iff b positive
        if (zb) { SetCmp(sa ? 1 : 0, 0, 0); return; }
        if (sa != sb) { SetCmp(sa, 0, 0); return; }        // negative one is smaller
        bool agtb = MagGT(a, b) != (sa != 0);              // sign flips magnitude order
        bool altb = MagGT(b, a) != (sa != 0);
        if (agtb == altb) { SetCmp(0, 0, 1); return; }     // equal magnitude
        SetCmp(altb ? 1 : 0, 0, 0);
    }

    // quiet = fucom-style (QNaN does not raise IE); ca/cb are RAW operand classes
    // (see BinaryOp); srcEmptyMask nonzero -> stack fault path.
    // Probed behavior: an IE (stack fault or NaN) writes the unordered codes 111
    // even when IE is UNMASKED — only the pop(s) are suppressed; an unmasked DE
    // suppresses nothing (codes + pops happen, the fault is simply deferred).
    void CompareOp(extFloat80_t a, extFloat80_t b, Cls ca, Cls cb,
                   int srcEmptyMask, int pops, bool quiet) {
        if (srcEmptyMask) {
            F.flags |= kIE | kSF;
            SetCmp(1, 1, 1);
            if (F.Masked(kIE)) F.Pops(pops);
            return;
        }
        if (IsNaNC(ca) || IsNaNC(cb)) {
            bool sig = (ca == cSNaN || cb == cSNaN || ca == cUnsupp || cb == cUnsupp);
            bool doPops = true;
            if (sig || !quiet) {
                F.flags |= kIE;
                doPops = F.Masked(kIE);
            }
            SetCmp(1, 1, 1);
            if (doPops) F.Pops(pops);
            return;
        }
        if (ca == cDenorm || cb == cDenorm) {
            // codes are still written, but an UNMASKED #D suppresses the pop(s)
            F.flags |= kDE;
            OrderedCmp(a, b);
            if (F.Masked(kDE)) F.Pops(pops);
            return;
        }
        OrderedCmp(a, b);
        F.Pops(pops);
    }

    // ---- pushes ------------------------------------------------------------------
    // Overflow-checked push preamble.  Returns: 0 = aborted, 1 = masked-overflow
    // handled (indefinite pushed, op done), 2 = slot free, proceed.
    int PushCheck() {
        int destPhys = (F.top - 1) & 7;
        if (!((F.empty >> destPhys) & 1)) {
            if (!StackFault(true)) return 0;
            F.PushSlot(); F.Put(0, kIndef); return 1;
        }
        return 2;
    }
    void PushVal(extFloat80_t v) { F.PushSlot(); F.Put(0, v); }

    // ---- memory ------------------------------------------------------------------
    static uint16_t Ld16(uint32_t ea) { uint16_t v; memcpy(&v, (void*)(uintptr_t)ea, 2); return v; }
    static uint32_t Ld32(uint32_t ea) { uint32_t v; memcpy(&v, (void*)(uintptr_t)ea, 4); return v; }
    static uint64_t Ld64(uint32_t ea) { uint64_t v; memcpy(&v, (void*)(uintptr_t)ea, 8); return v; }
    static void St16(uint32_t ea, uint16_t v) { memcpy((void*)(uintptr_t)ea, &v, 2); }
    static void St32(uint32_t ea, uint32_t v) { memcpy((void*)(uintptr_t)ea, &v, 4); }
    static void St64(uint32_t ea, uint64_t v) { memcpy((void*)(uintptr_t)ea, &v, 8); }
};

// ============================ transcendental support ==============================

struct TransConsts {
    extFloat80_t invFact[23];     // 1/k!  (k = 1..22; factorials exact in 64 bits)
    extFloat80_t invOdd[16];      // 1/(2k+1), k = 1..15
    extFloat80_t pi, piO2, piO4, pi3O4;
    extFloat80_t ln2, twoOverLn2, sqrt2;
};
static TransConsts g_tc;
static bool g_tcInit = false;

static void InitTrans() {
    if (g_tcInit) return;
    g_tcInit = true;
    softfloat_roundingMode = softfloat_round_near_even;
    extF80_roundingPrecision = 80;
    softfloat_exceptionFlags = 0;
    extFloat80_t f = kOne;
    g_tc.invFact[1] = kOne;
    for (int k = 2; k <= 22; ++k) {
        f = extF80_mul(f, i32_to_extF80(k));               // exact through 22!
        g_tc.invFact[k] = extF80_div(kOne, f);
    }
    for (int k = 1; k <= 15; ++k)
        g_tc.invOdd[k] = extF80_div(kOne, i32_to_extF80(2 * k + 1));
    // RN-rounded x87 constant family (host-verified patterns, see header comment)
    g_tc.pi    = MakeExt(0x4000, 0xC90FDAA22168C235ull);
    g_tc.piO2  = MakeExt(0x3FFF, 0xC90FDAA22168C235ull);
    g_tc.piO4  = MakeExt(0x3FFE, 0xC90FDAA22168C235ull);
    g_tc.pi3O4 = extF80_mul(g_tc.piO4, i32_to_extF80(3));
    g_tc.ln2   = MakeExt(0x3FFE, 0xB17217F7D1CF79ACull);
    g_tc.twoOverLn2 = MakeExt(0x4000, 0xB8AA3B295C17F0BCull);   // 2*log2(e), RN
    g_tc.sqrt2 = extF80_sqrt(MakeExt(0x4000, 0x8000000000000000ull));
    softfloat_exceptionFlags = 0;
}

// RN/80 environment for all internal transcendental math
static void TransEnv() {
    softfloat_roundingMode = softfloat_round_near_even;
    extF80_roundingPrecision = 80;
    softfloat_exceptionFlags = 0;
}

static extFloat80_t Neg(extFloat80_t v) { v.signExp ^= 0x8000; return v; }
static extFloat80_t Quieten(extFloat80_t v) { v.signif |= 0x4000000000000000ull; return v; }

// Horner: sum c[i] * x^i, i = 0..n-1
static extFloat80_t Poly(const extFloat80_t* c, int n, extFloat80_t x) {
    extFloat80_t s = c[n - 1];
    for (int i = n - 2; i >= 0; --i)
        s = extF80_add(extF80_mul(s, x), c[i]);
    return s;
}

// sin(r) / cos(r) kernels for |r| <= pi/4 (+ rounding slop)
static extFloat80_t SinKernel(extFloat80_t r) {
    extFloat80_t c[11], u = extF80_mul(r, r);
    c[0] = kOne;
    for (int k = 1; k <= 10; ++k) {
        c[k] = g_tc.invFact[2 * k + 1];
        if (k & 1) c[k] = Neg(c[k]);
    }
    return extF80_mul(r, Poly(c, 11, u));
}
static extFloat80_t CosKernel(extFloat80_t r) {
    extFloat80_t c[12], u = extF80_mul(r, r);
    c[0] = kOne;
    for (int k = 1; k <= 11; ++k) {
        c[k] = g_tc.invFact[2 * k];
        if (k & 1) c[k] = Neg(c[k]);
    }
    return Poly(c, 12, u);
}

// ---- 192-bit fixed-point trig reduction (the x87's own 66-bit pi/2) --------------

struct U192 { uint64_t w[3]; };                    // w[0] low

static bool GE192(const U192& a, const U192& b) {
    for (int i = 2; i >= 0; --i) {
        if (a.w[i] != b.w[i]) return a.w[i] > b.w[i];
    }
    return true;
}
static void Sub192(U192& a, const U192& b) {
    uint64_t borrow = 0;
    for (int i = 0; i < 3; ++i) {
        uint64_t d = a.w[i] - b.w[i];
        uint64_t br2 = (d > a.w[i]) ? 1u : 0u;
        uint64_t d2 = d - borrow;
        if (d2 > d) br2 = 1;
        a.w[i] = d2; borrow = br2;
    }
}
static void Shr1(U192& a) {
    a.w[0] = (a.w[0] >> 1) | (a.w[1] << 63);
    a.w[1] = (a.w[1] >> 1) | (a.w[2] << 63);
    a.w[2] >>= 1;
}
static void Shl192(U192& a, int k) {              // k in [0, 127]
    while (k >= 64) { a.w[2] = a.w[1]; a.w[1] = a.w[0]; a.w[0] = 0; k -= 64; }
    if (k) {
        a.w[2] = (a.w[2] << k) | (a.w[1] >> (64 - k));
        a.w[1] = (a.w[1] << k) | (a.w[0] >> (64 - k));
        a.w[0] <<= k;
    }
}

// hardware's 66-bit pi/2, as (value * 2^127): 0xC90FDAA22168C234C << 61
static const U192 kP192 = { { 0xC000000000000000ull, 0xC90FDAA22168C234ull, 0 } };

struct Red { int q; extFloat80_t r; };             // |x| = n*(pi/2)66 + r, q = n&3

// requires 2^-2 <= |x| < 2^63 normalized (sig has bit 63); e = unbiased exponent
static Red ReduceTrig(uint64_t sig, int e) {
    U192 X = { { sig, 0, 0 } };
    Shl192(X, e + 64);                             // X = |x| * 2^127
    U192 S = kP192;
    Shl192(S, 62);
    uint64_t n = 0;
    for (int i = 62; i >= 0; --i) {
        n <<= 1;
        if (GE192(X, S)) { Sub192(X, S); n |= 1; }
        Shr1(S);
    }
    // X = remainder in [0, P): round n to nearest (tie -> even)
    U192 half = kP192; Shr1(half);
    bool negR = false;
    bool gtHalf = GE192(X, half) && !(X.w[0] == half.w[0] && X.w[1] == half.w[1] && X.w[2] == half.w[2]);
    bool eqHalf = (X.w[0] == half.w[0] && X.w[1] == half.w[1] && X.w[2] == half.w[2]);
    if (gtHalf || (eqHalf && (n & 1))) {
        U192 t = kP192; Sub192(t, X); X = t;
        n += 1; negR = true;
    }
    Red out; out.q = (int)(n & 3);
    // convert X * 2^-127 (X < 2^128) to extF80, round to nearest-even
    if (!X.w[0] && !X.w[1]) { out.r = MakeExt(0, 0); return out; }
    int t;
    if (X.w[1]) { t = 127; while (!((X.w[1] >> (t - 64)) & 1)) --t; }
    else        { t = 63;  while (!((X.w[0] >> t) & 1)) --t; }
    uint64_t rsig; bool inc = false;
    if (t >= 64) {
        int sh = t - 63;                           // 1..64
        uint64_t rbit, sticky;
        if (sh == 64) {
            rsig = X.w[1];
            rbit = (X.w[0] >> 63) & 1;
            sticky = X.w[0] & 0x7FFFFFFFFFFFFFFFull;
        } else {
            rsig = (X.w[1] << (64 - sh)) | (X.w[0] >> sh);
            rbit = (X.w[0] >> (sh - 1)) & 1;
            sticky = (sh > 1) ? (X.w[0] & ((1ull << (sh - 1)) - 1)) : 0;
        }
        inc = rbit && (sticky || (rsig & 1));
    } else {
        rsig = X.w[0] << (63 - t);
    }
    int be = (t - 127) + 0x3FFF;
    if (inc) { ++rsig; if (!rsig) { rsig = 0x8000000000000000ull; ++be; } }
    out.r = MakeExt((uint16_t)((negR ? 0x8000 : 0) | be), rsig);
    return out;
}

// full sin+cos of a finite nonzero non-denormal-exempt |x| < 2^63.
// sign = sign of x.  Everything RN/80.
static void SinCos(extFloat80_t x, extFloat80_t* sinOut, extFloat80_t* cosOut) {
    bool neg = (x.signExp >> 15) & 1;
    int exp = x.signExp & 0x7FFF; uint64_t sig = x.signif;
    if (!exp) exp = 1;
    if (!(sig >> 63)) {
        struct exp32_sig64 nz = softfloat_normSubnormalExtF80Sig(sig);
        exp += nz.exp; sig = nz.sig;
    }
    int e = exp - 0x3FFF;
    extFloat80_t s, c;
    if (e <= -2) {                                 // |x| < 0.5 < pi/4: no reduction
        extFloat80_t ax = x; ax.signExp &= 0x7FFF;  // (possibly denormal — kernel is fine)
        s = SinKernel(ax); c = CosKernel(ax);
    } else {
        Red rd = ReduceTrig(sig, e);
        extFloat80_t ks = SinKernel(rd.r), kc = CosKernel(rd.r);
        switch (rd.q) {
        case 0: s = ks;      c = kc;      break;
        case 1: s = kc;      c = Neg(ks); break;
        case 2: s = Neg(ks); c = Neg(kc); break;
        default: s = Neg(kc); c = ks;     break;
        }
    }
    if (neg) s = Neg(s);
    *sinOut = s; *cosOut = c;
}

// atan(u) for 0 <= u <= 1 (RN/80): four half-angle steps + odd Taylor deg 15, x16
static extFloat80_t AtanPos(extFloat80_t u) {
    for (int k = 0; k < 4; ++k) {
        extFloat80_t t = extF80_add(kOne, extF80_mul(u, u));
        t = extF80_add(kOne, extF80_sqrt(t));
        u = extF80_div(u, t);
    }
    extFloat80_t c[8], u2 = extF80_mul(u, u);
    c[0] = kOne;
    for (int k = 1; k <= 7; ++k) {
        c[k] = g_tc.invOdd[k];
        if (k & 1) c[k] = Neg(c[k]);
    }
    extFloat80_t a = extF80_mul(u, Poly(c, 8, u2));
    return ScaleExact2k(a, 4);
}

// log2(x) for finite positive non-zero x (RN/80)
static extFloat80_t Log2Pos(extFloat80_t x) {
    int exp = x.signExp & 0x7FFF; uint64_t sig = x.signif;
    if (!exp) exp = 1;
    if (!(sig >> 63)) {
        struct exp32_sig64 nz = softfloat_normSubnormalExtF80Sig(sig);
        exp += nz.exp; sig = nz.sig;
    }
    int e = exp - 0x3FFF;
    extFloat80_t m = MakeExt(0x3FFF, sig);         // [1, 2)
    if (extF80_lt(g_tc.sqrt2, m)) { m = MakeExt(0x3FFE, sig); e += 1; }
    extFloat80_t s = extF80_div(extF80_sub(m, kOne), extF80_add(m, kOne));
    extFloat80_t c[14], s2 = extF80_mul(s, s);
    c[0] = kOne;
    for (int k = 1; k <= 13; ++k) c[k] = g_tc.invOdd[k];
    extFloat80_t L = extF80_mul(s, Poly(c, 14, s2));   // artanh(s) = ln(m)/2
    L = extF80_mul(L, g_tc.twoOverLn2);                // log2(m)
    return extF80_add(i32_to_extF80(e), L);
}

// expm1 kernel: 2^x - 1 = expm1(x*ln2), Taylor deg 20 (RN/80)
static extFloat80_t Expm1Pow2(extFloat80_t x) {
    extFloat80_t t = extF80_mul(x, g_tc.ln2);
    extFloat80_t c[20];
    for (int k = 0; k < 20; ++k) c[k] = g_tc.invFact[k + 1];
    return extF80_mul(t, Poly(c, 20, t));
}

// =============================== main exec ========================================

// int-store helpers with the "invalid supersedes PE" x87 rule (probed)
struct IntCvt { uint64_t val; bool invalid; bool inexact; bool up; };

static IntCvt CvtToI32(extFloat80_t v, uint8_t rc) {
    IntCvt r{};
    softfloat_roundingMode = rc; softfloat_exceptionFlags = 0;
    int32_t a = (int32_t)extF80_to_i32(v, rc, true);
    uint8_t sf = (uint8_t)softfloat_exceptionFlags;
    r.invalid = (sf & softfloat_flag_invalid) != 0;
    r.inexact = (sf & softfloat_flag_inexact) != 0;
    r.val = (uint64_t)(int64_t)a;
    if (!r.invalid && r.inexact) {
        softfloat_exceptionFlags = 0;
        int32_t b = (int32_t)extF80_to_i32(v, softfloat_round_minMag, false);
        uint64_t ma = a < 0 ? (uint64_t)(-(int64_t)a) : (uint64_t)a;
        uint64_t mb = b < 0 ? (uint64_t)(-(int64_t)b) : (uint64_t)b;
        r.up = ma > mb;
    }
    softfloat_exceptionFlags = 0;
    return r;
}
static IntCvt CvtToI64(extFloat80_t v, uint8_t rc) {
    IntCvt r{};
    softfloat_roundingMode = rc; softfloat_exceptionFlags = 0;
    int64_t a = (int64_t)extF80_to_i64(v, rc, true);
    uint8_t sf = (uint8_t)softfloat_exceptionFlags;
    r.invalid = (sf & softfloat_flag_invalid) != 0;
    r.inexact = (sf & softfloat_flag_inexact) != 0;
    r.val = (uint64_t)a;
    if (!r.invalid && r.inexact) {
        softfloat_exceptionFlags = 0;
        int64_t b = (int64_t)extF80_to_i64(v, softfloat_round_minMag, false);
        uint64_t ma = a < 0 ? (uint64_t)(-a) : (uint64_t)a;
        uint64_t mb = b < 0 ? (uint64_t)(-b) : (uint64_t)b;
        r.up = ma > mb;
    }
    softfloat_exceptionFlags = 0;
    return r;
}

// f32/f64 raw operand classification
static Cls ClassF32(uint32_t u) {
    uint32_t exp = (u >> 23) & 0xFF, frac = u & 0x7FFFFF;
    if (exp == 0xFF) return frac ? ((frac & 0x400000) ? cQNaN : cSNaN) : cInf;
    if (exp == 0) return frac ? cDenorm : cZero;
    return cNorm;
}
static Cls ClassF64(uint64_t u) {
    uint32_t exp = (uint32_t)(u >> 52) & 0x7FF; uint64_t frac = u & 0xFFFFFFFFFFFFFull;
    if (exp == 0x7FF) return frac ? ((frac & 0x8000000000000ull) ? cQNaN : cSNaN) : cInf;
    if (exp == 0) return frac ? cDenorm : cZero;
    return cNorm;
}

} // namespace

int X87ExactExec(CpuState& s, uint8_t op, uint8_t modrm, uint32_t ea) {
    InitTrans();

    // ---- deferred #MF delivery: pending unmasked exception + waiting instruction
    uint16_t rawCw, rawSw;
    memcpy(&rawCw, s.fpu.image + 0, 2);
    memcpy(&rawSw, s.fpu.image + 4, 2);
    bool pending = ((rawSw & ~rawCw) & 0x3F) != 0;
    if (op == 0x9B) {
        if (pending) return -1;
        Exec E{}; LoadImage(E.F, s.fpu.image); StoreImage(E.F, s.fpu.image);
        return 1;                                  // fnsave-equivalent renormalize
    }
    if (op < 0xD8 || op > 0xDF) return 0;
    const int mod = modrm >> 6, reg = (modrm >> 3) & 7, rm = modrm & 7;
    const bool noWait = (op == 0xDF && modrm == 0xE0) || (op == 0xDB && modrm == 0xE2) ||
                        (mod != 3 && reg == 7 && (op == 0xD9 || op == 0xDD));
    if (pending && !noWait) return -1;             // image untouched, like the thunk

    Exec E{};
    LoadImage(E.F, s.fpu.image);
    Fpu& F = E.F;
    const uint8_t grc = F.SfRound();
    bool decoded = true;

    // load a memory f32/f64 operand for arithmetic: returns false on unmasked abort
    // (flags already raised); cls/den out-params feed the shared gates
    // For ARITHMETIC uses the converted operand must stay SIGNALING when the raw
    // f32/f64 was an SNaN (the conversion quietens it): the x87's two-NaN rule
    // prefers a QNaN over an SNaN operand, which the softfloat propagation only
    // reproduces if it sees the SNaN as such.  (fld itself pushes the QUIET form.)
    auto LoadMemF32 = [&](extFloat80_t* out, Cls* cls) {
        uint32_t u = Exec::Ld32(ea);
        *cls = ClassF32(u);
        softfloat_exceptionFlags = 0;
        float32_t f; f.v = u;
        *out = f32_to_extF80(f);
        softfloat_exceptionFlags = 0;
        if (*cls == cSNaN) out->signif &= ~0x4000000000000000ull;
        return true;
    };
    auto LoadMemF64 = [&](extFloat80_t* out, Cls* cls) {
        uint64_t u = Exec::Ld64(ea);
        *cls = ClassF64(u);
        softfloat_exceptionFlags = 0;
        float64_t f; f.v = u;
        *out = f64_to_extF80(f);
        softfloat_exceptionFlags = 0;
        if (*cls == cSNaN) out->signif &= ~0x4000000000000000ull;
        return true;
    };

    // shared "binary arithmetic with a memory/int operand already converted" —
    // ST0 is dst; cb is the RAW class of the memory bits (drives #IA/#D)
    auto MemArith = [&](int kind, extFloat80_t b, Cls cb) {
        // kind: 0 add,1 mul,2 com,3 comp,4 sub,5 subr,6 div,7 divr
        bool e0 = F.Empty(0);
        extFloat80_t a = e0 ? kIndef : F.Get(0);
        Cls ca = e0 ? cQNaN : ClassOf(a);
        int em = e0 ? 1 : 0;
        uint8_t prec = F.Prec();
        switch (kind) {
        case 2: case 3:
            E.CompareOp(a, b, ca, cb, em, kind == 3 ? 1 : 0, false); return;
        case 0: E.BinaryOp(extF80_add, wAddSub, a, b, ca, cb, em, 0, 0, prec); return;
        case 1: E.BinaryOp(extF80_mul, wMul,    a, b, ca, cb, em, 0, 0, prec); return;
        case 4: E.BinaryOp(extF80_sub, wAddSub, a, b, ca, cb, em, 0, 0, prec); return;
        case 5: E.BinaryOp(extF80_sub, wAddSub, b, a, cb, ca, em, 0, 0, prec); return;
        case 6: E.BinaryOp(extF80_div, wDiv,    a, b, ca, cb, em, 0, 0, prec); return;
        default: E.BinaryOp(extF80_div, wDiv,   b, a, cb, ca, em, 0, 0, prec); return;
        }
    };

    // register-form binary: a = ST0, b = ST(i)
    auto RegArith = [&](int kind, int srcI, int dst, int pops) {
        bool eA = F.Empty(0), eB = F.Empty(srcI);
        extFloat80_t a = eA ? kIndef : F.Get(0);
        extFloat80_t b = eB ? kIndef : F.Get(srcI);
        Cls ca = ClassOf(a), cb = ClassOf(b);
        int em = (eA || eB) ? 1 : 0;
        uint8_t prec = F.Prec();
        switch (kind) {
        case 0: E.BinaryOp(extF80_add, wAddSub, a, b, ca, cb, em, dst, pops, prec); break;
        case 1: E.BinaryOp(extF80_mul, wMul,    a, b, ca, cb, em, dst, pops, prec); break;
        case 4: E.BinaryOp(extF80_sub, wAddSub, a, b, ca, cb, em, dst, pops, prec); break;  // ST0 - ST(i)
        case 5: E.BinaryOp(extF80_sub, wAddSub, b, a, cb, ca, em, dst, pops, prec); break;  // ST(i) - ST0
        case 6: E.BinaryOp(extF80_div, wDiv,    a, b, ca, cb, em, dst, pops, prec); break;  // ST0 / ST(i)
        default: E.BinaryOp(extF80_div, wDiv,   b, a, cb, ca, em, dst, pops, prec); break;  // ST(i) / ST0
        }
    };

    // fst/fstp to f32/f64 memory
    auto StoreMemFp = [&](bool dbl, bool pop) {
        F.c1 = 0;
        if (F.Empty(0)) {
            if (!E.StackFault(false)) return;
            if (dbl) Exec::St64(ea, 0xFFF8000000000000ull);
            else     Exec::St32(ea, 0xFFC00000u);
            if (pop) F.PopOne();
            return;
        }
        extFloat80_t v = F.Get(0);
        softfloat_roundingMode = grc; extF80_roundingPrecision = 80;
        softfloat_exceptionFlags = 0;
        uint64_t bits; uint8_t sf;
        if (dbl) { float64_t r = extF80_to_f64(v); bits = r.v; sf = (uint8_t)softfloat_exceptionFlags; }
        else     { float32_t r = extF80_to_f32(v); bits = r.v; sf = (uint8_t)softfloat_exceptionFlags; }
        bool up = false;
        if (sf & softfloat_flag_inexact) {
            softfloat_roundingMode = softfloat_round_minMag; softfloat_exceptionFlags = 0;
            uint64_t tb;
            if (dbl) { float64_t r = extF80_to_f64(v); tb = r.v; }
            else     { float32_t r = extF80_to_f32(v); tb = r.v; }
            uint64_t magMask = dbl ? 0x7FFFFFFFFFFFFFFFull : 0x7FFFFFFFull;
            up = (bits & magMask) > (tb & magMask);
        }
        softfloat_exceptionFlags = 0;
        uint16_t xf = X87FlagsFromSf(sf);
        if (xf & kIE) {                            // SNaN (or unsupported) source
            F.flags |= kIE;
            if (!F.Masked(kIE)) return;
            if (dbl) Exec::St64(ea, bits); else Exec::St32(ea, (uint32_t)bits);
            if (pop) F.PopOne();
            return;
        }
        // unmasked O/U on a memory store: nothing is stored, the stack does not
        // pop, and only the O/U flag is recorded (no PE — probed).  Unmasked #U
        // fires on tininess alone, even for an exactly-representable denormal.
        bool tinyStore = dbl ? (!(bits & 0x7FF0000000000000ull) && (bits & 0xFFFFFFFFFFFFFull))
                             : (!(bits & 0x7F800000u) && (bits & 0x7FFFFFu));
        if ((xf & kOE) && !F.Masked(kOE)) {
            F.flags |= kOE;
            return;
        }
        if (((xf & kUE) || tinyStore) && !F.Masked(kUE)) {
            F.flags |= kUE;
            return;
        }
        F.flags |= xf;
        if (dbl) Exec::St64(ea, bits); else Exec::St32(ea, (uint32_t)bits);
        F.c1 = up ? 1 : 0;
        if (pop) F.PopOne();
    };

    // fist/fistp
    auto StoreMemInt = [&](int size, bool pop) {   // size 16/32/64
        F.c1 = 0;
        if (F.Empty(0)) {
            if (!E.StackFault(false)) return;
            if (size == 16) Exec::St16(ea, 0x8000);
            else if (size == 32) Exec::St32(ea, 0x80000000u);
            else Exec::St64(ea, 0x8000000000000000ull);
            if (pop) F.PopOne();
            return;
        }
        extFloat80_t v = F.Get(0);
        IntCvt c = (size == 64) ? CvtToI64(v, grc) : CvtToI32(v, grc);
        bool inv = c.invalid;
        if (size == 16 && !inv) {
            int64_t x = (int64_t)c.val;
            if (x < -32768 || x > 32767) inv = true;
        }
        if (inv) {                                 // IE only — PE discarded (probed)
            F.flags |= kIE;
            if (!F.Masked(kIE)) return;
            if (size == 16) Exec::St16(ea, 0x8000);
            else if (size == 32) Exec::St32(ea, 0x80000000u);
            else Exec::St64(ea, 0x8000000000000000ull);
            if (pop) F.PopOne();
            return;
        }
        if (c.inexact) F.flags |= kPE;
        if (size == 16) Exec::St16(ea, (uint16_t)c.val);
        else if (size == 32) Exec::St32(ea, (uint32_t)c.val);
        else Exec::St64(ea, c.val);
        F.c1 = c.up ? 1 : 0;
        if (pop) F.PopOne();
    };

    // fild (exact)
    auto LoadInt = [&](int64_t v) {
        F.c1 = 0;
        int pc = E.PushCheck();
        if (pc != 2) return;
        softfloat_exceptionFlags = 0;
        E.PushVal(i64_to_extF80(v));
        softfloat_exceptionFlags = 0;
    };

    // in-place unary underflow (fchs/fabs/frndint/fsqrt/transcendental prologue)
    auto Underflow0 = [&]() {                      // returns true if masked-handled
        if (!E.StackFault(false)) return false;
        F.Put(0, kIndef);
        return true;
    };

    switch (op) {
    // ------------------------------------------------------------------ D8
    case 0xD8:
        if (mod != 3) {
            extFloat80_t b; Cls cb;
            LoadMemF32(&b, &cb);
            MemArith(reg, b, cb);
        } else {
            if (reg == 2 || reg == 3) {            // fcom/fcomp st(i)
                bool em = F.Empty(0) || F.Empty(rm);
                extFloat80_t a = em ? kIndef : F.Get(0), b = em ? kIndef : F.Get(rm);
                E.CompareOp(a, b, ClassOf(a), ClassOf(b), em ? 1 : 0,
                            reg == 3 ? 1 : 0, false);
            } else {
                RegArith(reg, rm, 0, 0);           // fadd/fmul/fsub/fsubr/fdiv/fdivr st,st(i)
            }
        }
        break;

    // ------------------------------------------------------------------ D9
    case 0xD9:
        if (mod != 3) {
            switch (reg) {
            case 0: {                              // fld m32
                F.c1 = 0;
                int pc = E.PushCheck();
                if (pc != 2) break;
                uint32_t u = Exec::Ld32(ea);
                Cls c = ClassF32(u);
                softfloat_exceptionFlags = 0;
                float32_t f; f.v = u;
                extFloat80_t v = f32_to_extF80(f);
                uint8_t sf = (uint8_t)softfloat_exceptionFlags;
                softfloat_exceptionFlags = 0;
                if (c == cDenorm) { if (!E.DenormGate()) break; }
                if (sf & softfloat_flag_invalid) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                }
                E.PushVal(v);
                break;
            }
            case 2: StoreMemFp(false, false); break;   // fst m32
            case 3: StoreMemFp(false, true); break;    // fstp m32
            case 5:                                     // fldcw
                F.cw = (Exec::Ld16(ea) & 0x1F3F) | 0x0040;
                break;
            case 7:                                     // fnstcw
                Exec::St16(ea, F.cw);
                break;
            default: decoded = false; break;            // fldenv/fnstenv/D9 /1
            }
        } else {
            switch (modrm) {
            case 0xC0: case 0xC1: case 0xC2: case 0xC3:
            case 0xC4: case 0xC5: case 0xC6: case 0xC7: {   // fld st(i)
                // source-EMPTY is checked before dest-overflow (probed: empty
                // source + occupied dest -> C1=0 underflow, indefinite pushed)
                F.c1 = 0;
                if (F.Empty(rm)) {
                    if (!E.StackFault(false)) break;
                    F.PushSlot(); F.Put(0, kIndef);
                    break;
                }
                extFloat80_t v = F.Get(rm);
                int pc = E.PushCheck();
                if (pc != 2) break;
                E.PushVal(v);
                break;
            }
            case 0xC8: case 0xC9: case 0xCA: case 0xCB:
            case 0xCC: case 0xCD: case 0xCE: case 0xCF: {   // fxch st(i)
                F.c1 = 0;
                bool e0 = F.Empty(0), ei = F.Empty(rm);
                if (e0 || ei) {
                    if (!E.StackFault(false)) break;
                    if (e0) F.Put(0, kIndef);
                    if (ei) F.Put(rm, kIndef);
                }
                extFloat80_t a = F.Get(0), b = F.Get(rm);
                F.Put(0, b); F.Put(rm, a);
                break;
            }
            case 0xE0:                                       // fchs
            case 0xE1: {                                     // fabs
                F.c1 = 0;
                if (F.Empty(0)) { Underflow0(); break; }
                extFloat80_t v = F.Get(0);
                if (modrm == 0xE0) v.signExp ^= 0x8000;
                else v.signExp &= 0x7FFF;
                F.Put(0, v);
                break;
            }
            case 0xE4: {                                     // ftst
                bool em = F.Empty(0);
                extFloat80_t a = em ? kIndef : F.Get(0);
                E.CompareOp(a, MakeExt(0, 0), ClassOf(a), cZero, em ? 1 : 0, 0, false);
                break;
            }
            case 0xE5: {                                     // fxam
                extFloat80_t v = F.r[F.Phys(0)];
                F.c1 = (v.signExp >> 15) & 1;
                if (F.Empty(0)) { F.c3 = 1; F.c2 = 0; F.c0 = 1; break; }
                switch (ClassOf(v)) {
                case cNorm:   F.c3 = 0; F.c2 = 1; F.c0 = 0; break;
                case cInf:    F.c3 = 0; F.c2 = 1; F.c0 = 1; break;
                case cZero:   F.c3 = 1; F.c2 = 0; F.c0 = 0; break;
                case cDenorm: F.c3 = 1; F.c2 = 1; F.c0 = 0; break;
                case cQNaN: case cSNaN: F.c3 = 0; F.c2 = 0; F.c0 = 1; break;
                default:      F.c3 = 0; F.c2 = 0; F.c0 = 0; break;   // unsupported
                }
                break;
            }
            case 0xE8: case 0xEA: case 0xEB: case 0xEC: case 0xED: case 0xEE: {
                // fld1 / fldl2e / fldpi / fldlg2 / fldln2 / fldz — RC-rounded
                F.c1 = 0;
                int pc = E.PushCheck();
                if (pc != 2) break;
                int rc = F.Rc();
                int up = (rc == 0 || rc == 2) ? 1 : 0;       // guard=1, sticky=1
                extFloat80_t v;
                switch (modrm) {
                case 0xE8: v = kOne; break;
                case 0xEA: v = MakeExt(0x3FFF, 0xB8AA3B295C17F0BBull + up); break;
                case 0xEB: v = MakeExt(0x4000, 0xC90FDAA22168C234ull + up); break;
                case 0xEC: v = MakeExt(0x3FFD, 0x9A209A84FBCFF798ull + up); break;
                case 0xED: v = MakeExt(0x3FFE, 0xB17217F7D1CF79ABull + up); break;
                default:   v = MakeExt(0, 0); break;
                }
                E.PushVal(v);
                break;
            }
            case 0xFA: {                                     // fsqrt
                F.c1 = 0;
                if (F.Empty(0)) { Underflow0(); break; }
                extFloat80_t a = F.Get(0);
                Cls ca = ClassOf(a);
                if (ca == cUnsupp) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(0, kIndef); break;
                }
                // negative operand: the invalid path exits before the denormal
                // check (probed: fsqrt(-denormal) -> IE only, no DE)
                bool negNonzero = (a.signExp >> 15) && !(ca == cZero);
                if (ca == cDenorm && !negNonzero && !E.DenormGate()) break;
                extFloat80_t out;
                auto sq = [](extFloat80_t x, extFloat80_t) { return extF80_sqrt(x); };
                if (!E.Deliver((BinFn)+sq, wMul, a, a, F.Prec(), &out)) break;
                F.Put(0, out);
                break;
            }
            case 0xFC: {                                     // frndint
                F.c1 = 0;
                if (F.Empty(0)) { Underflow0(); break; }
                extFloat80_t a = F.Get(0);
                Cls ca = ClassOf(a);
                if (ca == cUnsupp) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(0, kIndef); break;
                }
                if (ca == cDenorm && !E.DenormGate()) break;
                softfloat_roundingMode = grc; softfloat_exceptionFlags = 0;
                extFloat80_t r = extF80_roundToInt(a, grc, true);
                uint8_t sf = (uint8_t)softfloat_exceptionFlags;
                bool up = false;
                if (sf & softfloat_flag_inexact) {
                    softfloat_exceptionFlags = 0;
                    extFloat80_t t = extF80_roundToInt(a, softfloat_round_minMag, false);
                    up = MagGT(r, t);
                }
                softfloat_exceptionFlags = 0;
                if (sf & softfloat_flag_invalid) {           // SNaN
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(0, r); break;
                }
                if (sf & softfloat_flag_inexact) F.flags |= kPE;
                F.Put(0, r); F.c1 = up ? 1 : 0;
                break;
            }
            case 0xFD: {                                     // fscale
                F.c1 = 0;
                bool e0 = F.Empty(0), e1 = F.Empty(1);
                if (e0 || e1) {
                    if (!E.StackFault(false)) break;
                    F.Put(0, kIndef); break;
                }
                extFloat80_t a = F.Get(0), b = F.Get(1);
                Cls ca = ClassOf(a), cb = ClassOf(b);
                if (ca == cUnsupp || cb == cUnsupp) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(0, kIndef); break;
                }
                if (IsNaNC(ca) || IsNaNC(cb)) {              // propagate x87-style
                    softfloat_exceptionFlags = 0;
                    extFloat80_t r = extF80_mul(a, b);
                    bool inv = (softfloat_exceptionFlags & softfloat_flag_invalid) != 0;
                    softfloat_exceptionFlags = 0;
                    if (inv) {
                        F.flags |= kIE;
                        if (!F.Masked(kIE)) break;
                    }
                    F.Put(0, r); break;
                }
                if ((ca == cDenorm || cb == cDenorm) && !E.DenormGate()) break;
                if (cb == cInf) {
                    bool bneg = (b.signExp >> 15) & 1;
                    if (!bneg) {                             // * 2^+inf
                        if (ca == cZero) {
                            F.flags |= kIE;
                            if (!F.Masked(kIE)) break;
                            F.Put(0, kIndef); break;
                        }
                        F.Put(0, MakeExt((uint16_t)((a.signExp & 0x8000) | 0x7FFF),
                                         0x8000000000000000ull));
                        break;
                    } else {                                 // * 2^-inf
                        if (ca == cInf) {
                            F.flags |= kIE;
                            if (!F.Masked(kIE)) break;
                            F.Put(0, kIndef); break;
                        }
                        F.Put(0, MakeExt((uint16_t)(a.signExp & 0x8000), 0));
                        break;
                    }
                }
                if (ca == cZero || ca == cInf) { F.Put(0, a); break; }
                // n = ST1 truncated toward zero, clamped (saturates identically)
                int32_t n = 0;
                {
                    int be = b.signExp & 0x7FFF;
                    bool bneg = (b.signExp >> 15) & 1;
                    if (cb != cZero) {
                        int e = be - 0x3FFF;
                        uint64_t bs = b.signif;
                        if (be == 0) e = -0x3FFF;            // denormal: |b| < 1 -> 0
                        if (e >= 0) {
                            uint64_t mag = (e >= 63) ? 0xFFFFFFFFFFFFFFFFull
                                                     : (bs >> (63 - e));
                            n = (mag > 80000) ? 80000 : (int32_t)mag;
                            if (bneg) n = -n;
                        }
                    }
                }
                // unpack ST0, single rounding at exp+n
                int exp = a.signExp & 0x7FFF; uint64_t sig = a.signif;
                bool sign = (a.signExp >> 15) & 1;
                if (!exp) exp = 1;
                if (!(sig >> 63)) {
                    struct exp32_sig64 nz = softfloat_normSubnormalExtF80Sig(sig);
                    exp += nz.exp; sig = nz.sig;
                }
                auto scaleRun = [&](int32_t nn, uint8_t mode, uint8_t* sfOut) {
                    softfloat_roundingMode = mode;
                    extF80_roundingPrecision = 80;
                    softfloat_exceptionFlags = 0;
                    extFloat80_t r = softfloat_roundPackToExtF80(sign, exp + nn, sig, 0, 80);
                    *sfOut = (uint8_t)softfloat_exceptionFlags;
                    softfloat_exceptionFlags = 0;
                    return r;
                };
                uint8_t sf;
                extFloat80_t r = scaleRun(n, grc, &sf);
                bool up = false;
                if (sf & softfloat_flag_inexact) {
                    uint8_t sf2;
                    extFloat80_t t = scaleRun(n, softfloat_round_minMag, &sf2);
                    up = MagGT(r, t);
                }
                uint16_t xf = X87FlagsFromSf(sf);
                bool tiny = ((r.signExp & 0x7FFF) == 0) && r.signif;
                if ((xf & kOE) && !F.Masked(kOE)) {
                    uint8_t sfw; extFloat80_t w = scaleRun(n - 24576, grc, &sfw);
                    uint8_t sfw2; extFloat80_t w2 = scaleRun(n - 24576, softfloat_round_minMag, &sfw2);
                    F.flags |= kOE | (X87FlagsFromSf(sfw) & kPE);   // wrapped rounding's PE
                    F.Put(0, w); F.c1 = MagGT(w, w2) ? 1 : 0;
                    break;
                }
                if (!F.Masked(kUE) && ((xf & kUE) || tiny)) {
                    uint8_t sfw; extFloat80_t w = scaleRun(n + 24576, grc, &sfw);
                    uint8_t sfw2; extFloat80_t w2 = scaleRun(n + 24576, softfloat_round_minMag, &sfw2);
                    F.flags |= kUE | (X87FlagsFromSf(sfw) & kPE);
                    F.Put(0, w); F.c1 = MagGT(w, w2) ? 1 : 0;
                    break;
                }
                F.flags |= xf;
                F.Put(0, r); F.c1 = up ? 1 : 0;
                break;
            }
            // ------------------------- transcendentals -------------------------
            case 0xF0: {                                     // f2xm1
                F.c1 = 0;
                if (F.Empty(0)) { Underflow0(); break; }
                extFloat80_t a = F.Get(0);
                Cls ca = ClassOf(a);
                if (ca == cUnsupp) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(0, kIndef); break;
                }
                if (ca == cSNaN) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(0, Quieten(a)); break;
                }
                if (ca == cQNaN) { F.Put(0, a); break; }
                if (ca == cZero) { F.Put(0, a); break; }
                if (ca == cInf) {
                    if (a.signExp >> 15) F.Put(0, Neg(kOne));    // 2^-inf - 1 = -1
                    else F.Put(0, a);
                    break;
                }
                if (ca == cDenorm && !E.DenormGate()) break;
                // out of the defined domain (|x| > 1): this host passes the
                // operand through unchanged with PE (probed; SDM: "undefined")
                if ((a.signExp & 0x7FFF) > 0x3FFF ||
                    ((a.signExp & 0x7FFF) == 0x3FFF && a.signif > 0x8000000000000000ull)) {
                    F.flags |= kPE;
                    F.Put(0, a);
                    break;
                }
                TransEnv();
                extFloat80_t r = Expm1Pow2(a);
                softfloat_exceptionFlags = 0;
                F.flags |= kPE;
                if (((r.signExp & 0x7FFF) == 0) && r.signif) F.flags |= kUE;
                F.Put(0, r);
                break;
            }
            case 0xF1: {                                     // fyl2x
                F.c1 = 0;
                bool e0 = F.Empty(0), e1 = F.Empty(1);
                if (e0 || e1) {
                    if (!E.StackFault(false)) break;
                    F.Put(1, kIndef); F.PopOne(); break;
                }
                extFloat80_t x = F.Get(0), y = F.Get(1);
                Cls cx = ClassOf(x), cy = ClassOf(y);
                if (cx == cUnsupp || cy == cUnsupp) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(1, kIndef); F.PopOne(); break;
                }
                if (IsNaNC(cx) || IsNaNC(cy)) {
                    softfloat_exceptionFlags = 0;
                    extFloat80_t r = extF80_mul(x, y);
                    bool inv = (softfloat_exceptionFlags & softfloat_flag_invalid) != 0;
                    softfloat_exceptionFlags = 0;
                    if (inv) { F.flags |= kIE; if (!F.Masked(kIE)) break; }
                    F.Put(1, r); F.PopOne(); break;
                }
                if ((cx == cDenorm || cy == cDenorm) && !E.DenormGate()) break;
                bool xs = (x.signExp >> 15) & 1, ys = (y.signExp >> 15) & 1;
                if (cx == cZero) {
                    if (cy == cZero) {
                        F.flags |= kIE;
                        if (!F.Masked(kIE)) break;
                        F.Put(1, kIndef); F.PopOne(); break;
                    }
                    F.flags |= kZE;                          // y * -inf
                    if (!F.Masked(kZE)) break;
                    F.Put(1, MakeExt((uint16_t)((ys ? 0 : 0x8000) | 0x7FFF),
                                     0x8000000000000000ull));
                    F.PopOne(); break;
                }
                if (xs) {                                    // negative x
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(1, kIndef); F.PopOne(); break;
                }
                bool xIsOne = (x.signExp == 0x3FFF) && (x.signif == 0x8000000000000000ull);
                if (xIsOne) {
                    if (cy == cInf) {
                        F.flags |= kIE;
                        if (!F.Masked(kIE)) break;
                        F.Put(1, kIndef); F.PopOne(); break;
                    }
                    F.Put(1, MakeExt((uint16_t)(ys ? 0x8000 : 0), 0)); F.PopOne(); break;
                }
                if (cx == cInf) {
                    if (cy == cZero) {
                        F.flags |= kIE;
                        if (!F.Masked(kIE)) break;
                        F.Put(1, kIndef); F.PopOne(); break;
                    }
                    F.Put(1, MakeExt((uint16_t)((ys ? 0x8000 : 0) | 0x7FFF),
                                     0x8000000000000000ull));
                    F.PopOne(); break;
                }
                if (cy == cZero || cy == cInf) {
                    // sign of log2(x): x > 1 -> +, x < 1 -> -
                    bool lneg = (x.signExp & 0x7FFF) < 0x3FFF;
                    uint16_t sgn = (uint16_t)(((ys ? 1 : 0) ^ (lneg ? 1 : 0)) ? 0x8000 : 0);
                    if (cy == cZero) { F.Put(1, MakeExt(sgn, 0)); F.PopOne(); break; }
                    F.Put(1, MakeExt((uint16_t)(sgn | 0x7FFF), 0x8000000000000000ull));
                    F.PopOne(); break;
                }
                TransEnv();
                extFloat80_t L = Log2Pos(x);
                softfloat_exceptionFlags = 0;
                extFloat80_t r = extF80_mul(y, L);
                uint16_t xf = X87FlagsFromSf((uint8_t)softfloat_exceptionFlags);
                softfloat_exceptionFlags = 0;
                F.flags |= kPE | (xf & (kOE | kUE));
                F.Put(1, r); F.PopOne();
                break;
            }
            case 0xF3: {                                     // fpatan: atan2(ST1, ST0)
                F.c1 = 0;
                bool e0 = F.Empty(0), e1 = F.Empty(1);
                if (e0 || e1) {
                    if (!E.StackFault(false)) break;
                    F.Put(1, kIndef); F.PopOne(); break;
                }
                extFloat80_t x = F.Get(0), y = F.Get(1);
                Cls cx = ClassOf(x), cy = ClassOf(y);
                if (cx == cUnsupp || cy == cUnsupp) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    F.Put(1, kIndef); F.PopOne(); break;
                }
                if (IsNaNC(cx) || IsNaNC(cy)) {
                    softfloat_exceptionFlags = 0;
                    extFloat80_t r = extF80_mul(x, y);
                    bool inv = (softfloat_exceptionFlags & softfloat_flag_invalid) != 0;
                    softfloat_exceptionFlags = 0;
                    if (inv) { F.flags |= kIE; if (!F.Masked(kIE)) break; }
                    F.Put(1, r); F.PopOne(); break;
                }
                if ((cx == cDenorm || cy == cDenorm) && !E.DenormGate()) break;
                bool xs = (x.signExp >> 15) & 1, ys = (y.signExp >> 15) & 1;
                TransEnv();
                extFloat80_t r; bool inx = true;
                auto signed_ = [&](extFloat80_t v) { return ys ? Neg(v) : v; };
                if (cy == cInf) {
                    if (cx == cInf) r = signed_(xs ? g_tc.pi3O4 : g_tc.piO4);
                    else r = signed_(g_tc.piO2);
                } else if (cx == cInf) {
                    if (xs) r = signed_(g_tc.pi);
                    else { r = MakeExt((uint16_t)(ys ? 0x8000 : 0), 0); inx = false; }
                } else if (cy == cZero) {
                    if (xs) r = signed_(g_tc.pi);            // includes x = -0
                    else { r = MakeExt((uint16_t)(ys ? 0x8000 : 0), 0); inx = false; }
                } else if (cx == cZero) {
                    r = signed_(g_tc.piO2);
                } else {
                    extFloat80_t ax = x; ax.signExp &= 0x7FFF;
                    extFloat80_t ay = y; ay.signExp &= 0x7FFF;
                    extFloat80_t base;
                    if (!MagGT(ay, ax)) {                    // |y| <= |x|
                        base = AtanPos(extF80_div(ay, ax));
                        r = xs ? extF80_sub(g_tc.pi, base) : base;
                    } else {
                        base = AtanPos(extF80_div(ax, ay));
                        r = xs ? extF80_add(g_tc.piO2, base) : extF80_sub(g_tc.piO2, base);
                    }
                    r = signed_(r);
                }
                softfloat_exceptionFlags = 0;
                if (inx) F.flags |= kPE;
                if (((r.signExp & 0x7FFF) == 0) && r.signif) F.flags |= kUE;
                F.Put(1, r); F.PopOne();
                break;
            }
            case 0xFB:                                       // fsincos
            case 0xFE:                                       // fsin
            case 0xFF: {                                     // fcos
                F.c1 = 0;
                bool wantSin = (modrm != 0xFF);
                bool push = (modrm == 0xFB);
                if (F.Empty(0)) {
                    if (!E.StackFault(false)) break;
                    F.Put(0, kIndef);
                    if (push) { F.PushSlot(); F.Put(0, kIndef); }   // both results indef
                    break;
                }
                if (push) {
                    int destPhys = (F.top - 1) & 7;
                    if (!((F.empty >> destPhys) & 1)) {      // no room for the push
                        if (!E.StackFault(true)) break;
                        F.Put(0, kIndef);                    // old ST0 too (probed)
                        F.PushSlot(); F.Put(0, kIndef);
                        break;
                    }
                }
                extFloat80_t a = F.Get(0);
                Cls ca = ClassOf(a);
                if (ca == cUnsupp || ca == cSNaN || ca == cInf) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                    extFloat80_t r = (ca == cSNaN) ? Quieten(a) : kIndef;
                    F.Put(0, r);
                    if (push) E.PushVal(r);
                    F.c2 = 0;
                    break;
                }
                if (ca == cQNaN) {
                    F.Put(0, a);
                    if (push) E.PushVal(a);
                    F.c2 = 0;
                    break;
                }
                if (ca == cZero) {                           // exact
                    extFloat80_t sinv = a, cosv = kOne;
                    if (wantSin && !push) F.Put(0, sinv);
                    else if (!wantSin) F.Put(0, cosv);
                    else { F.Put(0, sinv); E.PushVal(cosv); }
                    F.c2 = 0;
                    break;
                }
                // |x| >= 2^63: unreduced, operand untouched
                if ((a.signExp & 0x7FFF) >= 0x403E) { F.c2 = 1; break; }
                if (ca == cDenorm && !E.DenormGate()) break;
                TransEnv();
                extFloat80_t sinv, cosv;
                SinCos(a, &sinv, &cosv);
                softfloat_exceptionFlags = 0;
                F.flags |= kPE;
                extFloat80_t chk = wantSin ? sinv : cosv;
                if (((chk.signExp & 0x7FFF) == 0) && chk.signif) F.flags |= kUE;
                if (wantSin && !push) F.Put(0, sinv);
                else if (!wantSin) F.Put(0, cosv);
                else { F.Put(0, sinv); E.PushVal(cosv); }
                F.c2 = 0;
                break;
            }
            default: decoded = false; break;
            }
        }
        break;

    // ------------------------------------------------------------------ DA
    case 0xDA:
        if (mod != 3) {                            // fiadd/fimul/ficom/ficomp/... m32int
            int32_t iv = (int32_t)Exec::Ld32(ea);
            softfloat_exceptionFlags = 0;
            extFloat80_t b = i32_to_extF80(iv);
            softfloat_exceptionFlags = 0;
            MemArith(reg, b, cNorm);
        } else if (modrm == 0xE9) {                // fucompp
            bool em = F.Empty(0) || F.Empty(1);
            extFloat80_t a = em ? kIndef : F.Get(0), b = em ? kIndef : F.Get(1);
            E.CompareOp(a, b, ClassOf(a), ClassOf(b), em ? 1 : 0, 2, true);
        } else decoded = false;
        break;

    // ------------------------------------------------------------------ DB
    case 0xDB:
        if (mod != 3) {
            switch (reg) {
            case 0: LoadInt((int32_t)Exec::Ld32(ea)); break; // fild m32
            case 2: StoreMemInt(32, false); break;           // fist m32
            case 3: StoreMemInt(32, true); break;            // fistp m32
            case 5: {                                        // fld m80 (raw, no exceptions)
                F.c1 = 0;
                int pc = E.PushCheck();
                if (pc != 2) break;
                extFloat80_t v;
                memcpy(&v.signif, (void*)(uintptr_t)ea, 8);
                memcpy(&v.signExp, (void*)(uintptr_t)(ea + 8), 2);
                E.PushVal(v);
                break;
            }
            case 7: {                                        // fstp m80 (raw)
                F.c1 = 0;
                if (F.Empty(0)) {
                    if (!E.StackFault(false)) break;
                    memcpy((void*)(uintptr_t)ea, &kIndef.signif, 8);
                    memcpy((void*)(uintptr_t)(ea + 8), &kIndef.signExp, 2);
                    F.PopOne(); break;
                }
                extFloat80_t v = F.Get(0);
                memcpy((void*)(uintptr_t)ea, &v.signif, 8);
                memcpy((void*)(uintptr_t)(ea + 8), &v.signExp, 2);
                F.PopOne();
                break;
            }
            default: decoded = false; break;
            }
        } else if (modrm == 0xE2) {                          // fnclex
            F.flags = 0;
        } else decoded = false;
        break;

    // ------------------------------------------------------------------ DC
    case 0xDC:
        if (mod != 3) {
            extFloat80_t b; Cls cb;
            LoadMemF64(&b, &cb);
            MemArith(reg, b, cb);
        } else {
            switch (reg) {
            case 0: RegArith(0, rm, rm, 0); break;           // fadd st(i),st
            case 1: RegArith(1, rm, rm, 0); break;           // fmul st(i),st
            case 4: RegArith(4, rm, rm, 0); break;           // fsubr st(i),st: st - st(i)...
            case 5: RegArith(5, rm, rm, 0); break;
            case 6: RegArith(6, rm, rm, 0); break;
            case 7: RegArith(7, rm, rm, 0); break;
            default: decoded = false; break;
            }
            // NOTE the DC register encodings reverse the mnemonic pair:
            //   DC E0+i = FSUBR ST(i),ST = ST0 - ST(i)  -> kind 4 (a - b)
            //   DC E8+i = FSUB  ST(i),ST = ST(i) - ST0  -> kind 5 (b - a)
            //   DC F0+i = FDIVR ST(i),ST = ST0 / ST(i)  -> kind 6 (a / b)
            //   DC F8+i = FDIV  ST(i),ST = ST(i) / ST0  -> kind 7 (b / a)
            // which is exactly the same kind numbering as D8 — no swap needed.
        }
        break;

    // ------------------------------------------------------------------ DD
    case 0xDD:
        if (mod != 3) {
            switch (reg) {
            case 0: {                                        // fld m64
                F.c1 = 0;
                int pc = E.PushCheck();
                if (pc != 2) break;
                uint64_t u = Exec::Ld64(ea);
                Cls c = ClassF64(u);
                softfloat_exceptionFlags = 0;
                float64_t f; f.v = u;
                extFloat80_t v = f64_to_extF80(f);
                uint8_t sf = (uint8_t)softfloat_exceptionFlags;
                softfloat_exceptionFlags = 0;
                if (c == cDenorm) { if (!E.DenormGate()) break; }
                if (sf & softfloat_flag_invalid) {
                    F.flags |= kIE;
                    if (!F.Masked(kIE)) break;
                }
                E.PushVal(v);
                break;
            }
            case 2: StoreMemFp(true, false); break;          // fst m64
            case 3: StoreMemFp(true, true); break;           // fstp m64
            case 7: {                                        // fnstsw m16 (no-wait)
                uint16_t sw = (uint16_t)(F.flags | (F.c0 << 8) | (F.c1 << 9) |
                                         (F.c2 << 10) | (F.top << 11) | (F.c3 << 14));
                if ((F.flags & ~F.cw) & 0x3F) sw |= 0x8080;
                Exec::St16(ea, sw);
                break;
            }
            default: decoded = false; break;
            }
        } else {
            switch (reg) {
            case 0:                                          // ffree st(i)
                F.c1 = 0;
                F.empty |= 1u << F.Phys(rm);
                break;
            case 2: case 3: {                                // fst/fstp st(i)
                F.c1 = 0;
                if (F.Empty(0)) {
                    if (!E.StackFault(false)) break;
                    F.Put(rm, kIndef);
                    if (reg == 3) F.PopOne();
                    break;
                }
                F.Put(rm, F.Get(0));
                if (reg == 3) F.PopOne();
                break;
            }
            case 4: case 5: {                                // fucom/fucomp st(i)
                bool em = F.Empty(0) || F.Empty(rm);
                extFloat80_t a = em ? kIndef : F.Get(0), b = em ? kIndef : F.Get(rm);
                E.CompareOp(a, b, ClassOf(a), ClassOf(b), em ? 1 : 0,
                            reg == 5 ? 1 : 0, true);
                break;
            }
            default: decoded = false; break;
            }
        }
        break;

    // ------------------------------------------------------------------ DE
    case 0xDE:
        if (mod != 3) {                            // integer arith m16
            int32_t iv = (int16_t)Exec::Ld16(ea);
            softfloat_exceptionFlags = 0;
            extFloat80_t b = i32_to_extF80(iv);
            softfloat_exceptionFlags = 0;
            MemArith(reg, b, cNorm);
        } else if (modrm == 0xD9) {                // fcompp
            bool em = F.Empty(0) || F.Empty(1);
            extFloat80_t a = em ? kIndef : F.Get(0), b = em ? kIndef : F.Get(1);
            E.CompareOp(a, b, ClassOf(a), ClassOf(b), em ? 1 : 0, 2, false);
        } else {
            switch (reg) {
            case 0: RegArith(0, rm, rm, 1); break;           // faddp
            case 1: RegArith(1, rm, rm, 1); break;           // fmulp
            case 4: RegArith(4, rm, rm, 1); break;           // fsubrp: ST0 - ST(i)
            case 5: RegArith(5, rm, rm, 1); break;           // fsubp:  ST(i) - ST0
            case 6: RegArith(6, rm, rm, 1); break;           // fdivrp: ST0 / ST(i)
            case 7: RegArith(7, rm, rm, 1); break;           // fdivp:  ST(i) / ST0
            default: decoded = false; break;
            }
        }
        break;

    // ------------------------------------------------------------------ DF
    case 0xDF:
        if (mod != 3) {
            switch (reg) {
            case 0: LoadInt((int16_t)Exec::Ld16(ea)); break; // fild m16
            case 2: StoreMemInt(16, false); break;           // fist m16
            case 3: StoreMemInt(16, true); break;            // fistp m16
            case 5: LoadInt((int64_t)Exec::Ld64(ea)); break; // fild m64
            case 7: StoreMemInt(64, true); break;            // fistp m64
            default: decoded = false; break;
            }
        } else if (modrm == 0xE0) {                          // fnstsw ax (no-wait)
            uint16_t sw = (uint16_t)(F.flags | (F.c0 << 8) | (F.c1 << 9) |
                                     (F.c2 << 10) | (F.top << 11) | (F.c3 << 14));
            if ((F.flags & ~F.cw) & 0x3F) sw |= 0x8080;
            s.r[EAX] = (s.r[EAX] & 0xFFFF0000u) | sw;
        } else decoded = false;
        break;

    default:
        decoded = false;
        break;
    }

    if (!decoded) return 0;                        // BadDecode: image untouched
    StoreImage(F, s.fpu.image);
    return 1;
}

void X87ExactOnImage(uint8_t image[108], uint8_t op, uint8_t modrm, uint32_t ea,
                     int* outcome) {
    CpuState s{};
    memcpy(s.fpu.image, image, 108);
    int r = X87ExactExec(s, op, modrm, ea);
    memcpy(image, s.fpu.image, 108);
    if (outcome) *outcome = r;
}

} // namespace tj::engine
