"""Extract the game's global data segment from default.xbe into a single image the
ported C code links against. Static-recompilation style: we preserve .rdata + .data
byte-for-byte at their original virtual addresses, so every DAT_######## reference in
the decompiled code resolves by simple indexing (image[VA - base]). BSS (uninitialized
tail of .data) is zero-filled at load, matching Xbox startup.

Outputs (into port/src/game/generated/):
  data_image.bin   initialized bytes, VA image_base .. init_end
  data_image.h     base/size/init-size constants + accessor macros
"""
import struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
XBE = os.path.join(ROOT, "extracted", "default.xbe")
OUT = os.path.join(ROOT, "port", "src", "game", "generated")
os.makedirs(OUT, exist_ok=True)

data = open(XBE, "rb").read()
base_addr, = struct.unpack_from("<I", data, 0x104)
num_sections, section_hdr_addr = struct.unpack_from("<II", data, 0x11C)

def hva(a): return a - base_addr

secs = []
s = hva(section_hdr_addr)
for i in range(num_sections):
    flags, vaddr, vsize, raw_off, raw_size, name_addr = struct.unpack_from("<6I", data, s + i*0x38)
    name = data[hva(name_addr):hva(name_addr)+32].split(b"\0")[0].decode("latin-1")
    secs.append((name, vaddr, vsize, raw_off, raw_size))

by = {n: (v, vs, ro, rs) for n, v, vs, ro, rs in secs}
rdata = by[".rdata"]
ddata = by[".data"]

# The global image spans from .rdata start through the end of .data's virtual size.
image_base = rdata[0]
image_end  = ddata[0] + ddata[1]          # data vaddr + data vsize (includes BSS)
init_end   = ddata[0] + ddata[3]          # data vaddr + data raw_size (last stored byte)
image_size = image_end - image_base
init_size  = init_end - image_base

# Build the initialized blob: copy each section's raw bytes to its VA offset.
blob = bytearray(init_size)
for name, vaddr, vsize, raw_off, raw_size in secs:
    if vaddr < image_base or vaddr >= init_end:
        continue
    if raw_size == 0:
        continue
    dst = vaddr - image_base
    n = min(raw_size, init_size - dst)
    if n > 0:
        blob[dst:dst+n] = data[raw_off:raw_off+n]

with open(os.path.join(OUT, "data_image.bin"), "wb") as f:
    f.write(blob)

with open(os.path.join(OUT, "data_image.h"), "w") as f:
    f.write("""// GENERATED by port/tools/extract_data_image.py -- do not edit.
// Global data segment of default.xbe preserved at original virtual addresses.
#pragma once
#include <cstdint>

namespace tj::game {

constexpr uint32_t kDataImageBase = 0x%08Xu;   // first VA covered (.rdata start)
constexpr uint32_t kDataImageEnd  = 0x%08Xu;   // one past last VA (.data vaddr+vsize)
constexpr uint32_t kDataImageSize = 0x%08Xu;   // full span incl. BSS (zero-filled)
constexpr uint32_t kDataInitSize  = 0x%08Xu;   // bytes loaded from data_image.bin

// The runtime memory holding the whole data segment (allocated + zeroed at startup,
// then the first kDataInitSize bytes overwritten from data_image.bin).
extern uint8_t* g_dataImage;

// Load data_image.bin next to the executable and populate g_dataImage. Returns false
// on failure. Call once before any ported game function runs.
bool LoadDataImage(const char* binPath);

// Resolve an original virtual address to a live pointer in the data image.
inline void* DAT(uint32_t va) { return g_dataImage + (va - kDataImageBase); }

// Typed accessors used by ported functions (raw-offset stage).
template <class T> inline T&  Ref(uint32_t va)  { return *reinterpret_cast<T*>(DAT(va)); }
inline float&    Flt(uint32_t va) { return Ref<float>(va); }
inline int32_t&  I32(uint32_t va) { return Ref<int32_t>(va); }
inline uint32_t& U32(uint32_t va) { return Ref<uint32_t>(va); }
inline uint8_t&  U8 (uint32_t va) { return Ref<uint8_t>(va); }

} // namespace tj::game
""" % (image_base, image_end, image_size, init_size))

print(f"image_base=0x{image_base:X} init_end=0x{init_end:X} image_end=0x{image_end:X}")
print(f"init_size={init_size} bytes ({init_size/1024:.0f} KB), full span={image_size/1024/1024:.1f} MB")
print("wrote", os.path.join(OUT, "data_image.bin"), "and data_image.h")
