// AUTO-GENERATED by scratchpad gen_fs_sites. fs:[KPCR] read sites to redirect.
// Each: {va, instrLen, dispOffsetInInstr, origDisp}. Rewrite fs(0x64)->ds(0x3E)
// prefix and add the fake-KPCR base to the disp32 (at va+dispOff).
#pragma once
#include <cstdint>
namespace tj { namespace hybrid {
struct FsSite { uint32_t va; uint8_t len; uint8_t dispOff; uint32_t disp; };
static const FsSite kFsSites[] = {
  {0x00074519, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x00074543, 8, 4, 0x24},  // .text movzx eax, byte ptr fs:[0x24]
  {0x0007454f, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x0007456b, 8, 4, 0x24},  // .text movzx eax, byte ptr fs:[0x24]
  {0x00074577, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x0007461f, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x0007463b, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x00075e7f, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x00076337, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x00076436, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x00076482, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x0007654f, 8, 4, 0x24},  // .text movzx eax, byte ptr fs:[0x24]
  {0x0007655b, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x00076578, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x000783d9, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x0007844d, 6, 2, 0x20},  // .text mov eax, dword ptr fs:[0x20]
  {0x0008f928, 8, 4, 0x24},  // .text movzx eax, byte ptr fs:[0x24]
  {0x0008f93e, 6, 2, 0x28},  // .text mov eax, dword ptr fs:[0x28]
  {0x0009df55, 6, 2, 0x20},  // D3D mov eax, dword ptr fs:[0x20]
  {0x000a9bb3, 8, 4, 0x24},  // DSOUND movzx eax, byte ptr fs:[0x24]
  {0x000a9be9, 6, 2, 0x58},  // DSOUND mov eax, dword ptr fs:[0x58]
  {0x000a9c0e, 6, 2, 0x58},  // DSOUND mov eax, dword ptr fs:[0x58]
  {0x000a9db5, 8, 4, 0x24},  // DSOUND movzx eax, byte ptr fs:[0x24]
  {0x000af695, 8, 4, 0x24},  // DSOUND movzx eax, byte ptr fs:[0x24]
};
static const int kFsSiteCount = 24;
}}
